# Generated by Django 4.0.2 on 2022-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
